# Output gene lists should be just human genes
get.comparison.hgnc.genesets <- function(pair,gene_groups,mouse_to_human_homologs,fileRoot){
    ########################
    #### ARGUMENT CHECKS ###
    ########################
    # Check the folder for saving the text files exists
    if(!file.exists(fileRoot)){stop("ERROR: fileRoot does not exist")}
    # If fileRoot doesn't end in a "/" then add it
    if(length(grep("/$",fileRoot))==0){fileRoot=sprintf("%s/",fileRoot)}
    # Check the folder for saving the text files contains the standard directories
    if(!file.exists(sprintf("%sFigures",fileRoot))){stop("ERROR: 'Figures' directory not found within 'fileRoot'. Did you pass the correct folder path?")}
    filePath = sprintf("%sCellTypeComparison_text_files/",fileRoot)
    if(!file.exists(filePath)){  dir.create(filePath)  }
    # Check pair has all the correct entries
    if(sum(names(pair)!=c("fileRoot1","ct1","fileRoot2","ct2"))==4){stop("ERROR: pair should be a list containing 'fileRoot1', 'ct1', 'fileRoot2' and 'ct2'.")}
    # Check gene groups has at least two entries
    if(length(names(gene_groups[[1]]))<2){stop("ERROR: gene_groups should be a list with a sublist for each celltype")}
    
    ############################################################################
    ### FIND HOW SPECIFIC GENES MOST SPECIFIC TO CELLTYPE1 ARE IN CELLTYPE 2 ###
    ############################################################################
    ff1 = gsub("_CutOff0.5_percentile_StepSize_0.1","",pair$fileRoot1)
    ff2 = gsub("_CutOff0.5_percentile_StepSize_0.1","",pair$fileRoot2)
    ct1_dat = get.human.genegroup.homologs(gene_groups[[ff1]][[pair$ct1]]$cell_groups,mouse_to_human_homologs)
    ct2_dat = get.human.genegroup.homologs(gene_groups[[ff2]][[pair$ct2]]$cell_groups,mouse_to_human_homologs)
    ct1_specific = as.character(ct1_dat[ct1_dat$percentile==0.9,]$hgnc_symbol)
    ct2_specific = as.character(ct2_dat[ct2_dat$percentile==0.9,]$hgnc_symbol)
    ct2_high   = as.character(ct2_dat[ct2_dat$percentile>=0.6 & ct2_dat$percentile<0.9,]$hgnc_symbol)
    ct2_medium = as.character(ct2_dat[ct2_dat$percentile>=0.3 & ct2_dat$percentile<0.6,]$hgnc_symbol)
    ct2_low    = as.character(ct2_dat[ct2_dat$percentile>=0 & ct2_dat$percentile<0.3,]$hgnc_symbol)
    specific_to_both        = intersect(ct1_specific,ct2_specific) 
    ct1_specific_ct2_high   = intersect(ct1_specific,ct2_high) 
    ct1_specific_ct2_medium = intersect(ct1_specific,ct2_medium) 
    ct1_specific_ct2_low    = intersect(ct1_specific,ct2_low) 
    ct2_group  = data.frame(file1=ff1,file2=ff2,cell1=pair$ct1,cell2=pair$ct2,hgnc_symbol=ct1_specific,group="Specific to Both")
    ct2_group$group = as.character(ct2_group$group)
    if(sum(ct2_group$hgnc_symbol %in% ct1_specific_ct2_high)>0){
        ct2_group[ct2_group$hgnc_symbol %in% ct1_specific_ct2_high,]$group="High Expressed" }
    if(sum(ct2_group$hgnc_symbol %in% ct1_specific_ct2_medium)>0){
        ct2_group[ct2_group$hgnc_symbol %in% ct1_specific_ct2_medium,]$group="Expressed" }
    if(sum(ct2_group$hgnc_symbol %in% ct1_specific_ct2_low)>0){
        ct2_group[ct2_group$hgnc_symbol %in% ct1_specific_ct2_low,]$group="Low Expressed" }
    ct2_group$group = factor(ct2_group$group,levels=c("Specific to Both","High Expressed","Expressed","Low Expressed"))
    
    ###############################
    ### SAVE GENE LISTS TO FILE ###
    ###############################
    shortF <- function(x){return(gsub("celltype_data_|_thresh0_trim0|_CutOff0.5_percentile_StepSize_0.1","",x))}
    wriList <- function(groupVals,groupName,tagA,tagB,res_path,pair){
        # Shorten filenames
        ff1_short = shortF(pair$fileRoot1)
        ff2_short = shortF(pair$fileRoot2)
        # Save the list
        listWTheader = c(tagA,tagB,unique(as.character(groupVals[groupVals$group==groupName,"hgnc_symbol"])))
        fName = sprintf("%s%s_%s_Specific_VS_%s_%s_%s.txt",res_path,pair$ct1,ff1_short,pair$ct2,ff2_short,groupName)
        write.table(listWTheader,file=fName,quote=FALSE,row.names=FALSE,col.names=FALSE)
    }
    
    tagA="Generated by the function in get.comparison.hgnc.genesets.r"
    tagB=sprintf("Outputs whether genes which are specific to cell type 1 [%s] are (specific) (high expressed) (expressed) or (low expressed) in cell type 2 [%s]",pair$ct1,pair$ct2)
    for(groupName in unique(ct2_group$group)){
        wriList(groupVals=ct2_group,groupName=groupName,tagA,tagB,res_path=filePath,pair=pair)
    }
    
    group_proportions = c(celltype1=pair$ct1,celltype2=pair$ct2,file1=shortF(pair$fileRoot1),file2=shortF(pair$fileRoot2),table(ct2_group$group)/sum(table(ct2_group$group)))
    return(list(ct2_group=ct2_group,proportions=group_proportions))
}

